In [ ]:
#Naive Bayes

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
data = pd.read_csv("train.csv")
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
print(x)
print(y)
print(len(y))

[[-3.83886455 -0.79419939]
 [-0.25112608 -2.30745538]
 [-4.05764485  0.87093065]
 ...
 [-4.25128436 -0.61626052]
 [-4.86654642  0.69290766]
 [-0.24833006 -2.57717437]]
[1. 2. 1. 1. 2. 1. 0. 2. 1. 1. 1. 2. 2. 0. 2. 1. 2. 2. 2. 1. 1. 1. 0. 0.
 2. 0. 1. 2. 1. 1. 1. 2. 1. 0. 1. 1. 2. 0. 1. 2. 0. 0. 1. 2. 1. 1. 0. 1.
 2. 2. 2. 0. 2. 2. 2. 1. 2. 2. 1. 2. 0. 0. 1. 0. 1. 0. 0. 0. 2. 0. 1. 1.
 0. 1. 1. 1. 0. 1. 0. 0. 2. 0. 2. 2. 1. 2. 0. 2. 1. 1. 0. 1. 1. 0. 0. 0.
 1. 0. 0. 1. 2. 2. 1. 1. 0. 1. 2. 2. 2. 1. 0. 2. 2. 2. 2. 2. 2. 2. 1. 1.
 2. 2. 1. 1. 0. 1. 0. 2. 0. 0. 2. 0. 1. 0. 0. 2. 0. 0. 0. 0. 2. 2. 1. 1.
 0. 1. 0. 0. 1. 0. 0. 1. 2. 1. 2. 0. 1. 2. 0. 0. 0. 0. 2. 1. 0. 0. 2. 0.
 0. 2. 0. 1. 2. 0. 0. 2. 1. 1. 2. 2. 0. 1. 1. 0. 1. 2. 0. 2. 1. 0. 2. 0.
 0. 2. 1. 0. 2. 0. 0. 2. 0. 2. 2. 1. 0. 1. 0. 0. 2. 2. 0. 1. 2. 0. 0. 0.
 0. 0. 0. 2. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 2. 1. 1. 1. 0. 0. 2. 0. 1. 1.
 2. 1. 1. 1. 1. 0. 1. 0. 1. 2. 2. 0. 1. 1. 0. 0. 2. 2. 1. 0. 1. 0. 2. 0.
 1. 0. 0. 0. 2. 2. 2. 2. 0. 0

In [6]:
print(np.unique(y))

[0. 1. 2.]


In [22]:

def gaussian_pdf(x,mean,std):
  eps = 1e-9
  std = np.maximum(std,eps)
  exponent = np.exp(-0.5*((x-mean)/std)**2)
  return (1/(np.sqrt(2*np.pi)*std))*exponent


def naive_bayes(X,classes,cls_prior,feature_stats):
  y_pred = []
  for x in X:
    cls_prob = {}
    for i,cls in enumerate(classes):
      log_prior = np.log(cls_prior[i])
      log_likelihood = np.sum(np.log(gaussian_pdf(x,feature_stats[cls]["mean"],feature_stats[cls]["std"])))
      cls_prob[cls] = log_prior + log_likelihood
    y_pred.append(max(cls_prob,key=cls_prob.get))
  return y_pred

classes = np.unique(y)

cls_prior = []

feature_stats = {}

for cls in classes:
  x_cls = x[y==cls]
  cls_prior.append(len(x_cls)/len(x))
  feature_stats[cls] = {
            "mean": np.mean(x_cls, axis=0),
            "std": np.std(x_cls, axis=0)
        }
print(cls_prior)
print(feature_stats)

y_pred = naive_bayes(x,classes,cls_prior,feature_stats)
print("Y pred : ",np.array(y_pred))
print()
print(y)


[0.3380952380952381, 0.3345238095238095, 0.3273809523809524]
{0.0: {'mean': array([3.99410393, 0.0114584 ]), 'std': array([1.2203854 , 1.22718441])}, 1.0: {'mean': array([-4.01945688, -0.00633294]), 'std': array([1.06056182, 0.97914089])}, 2.0: {'mean': array([-0.23482754, -4.0209672 ]), 'std': array([1.19775468, 1.14860914])}}
Y pred :  [1. 2. 1. 1. 2. 1. 0. 2. 1. 1. 1. 2. 2. 0. 2. 1. 2. 2. 2. 1. 1. 1. 0. 0.
 2. 0. 1. 2. 1. 1. 1. 2. 1. 0. 1. 1. 2. 0. 1. 2. 0. 0. 1. 2. 1. 1. 0. 1.
 2. 2. 2. 0. 2. 2. 2. 1. 2. 2. 1. 2. 0. 0. 1. 0. 1. 0. 0. 0. 2. 0. 1. 1.
 0. 1. 1. 1. 0. 1. 0. 0. 2. 0. 2. 2. 1. 2. 0. 2. 1. 1. 0. 1. 1. 0. 0. 0.
 1. 0. 0. 1. 2. 2. 1. 1. 0. 1. 2. 2. 2. 1. 0. 2. 2. 2. 2. 0. 2. 2. 1. 1.
 2. 2. 1. 1. 0. 1. 0. 2. 0. 0. 2. 0. 1. 0. 0. 2. 0. 0. 0. 2. 2. 2. 1. 1.
 0. 1. 0. 0. 1. 0. 0. 1. 2. 1. 2. 0. 1. 2. 0. 0. 0. 0. 2. 1. 0. 0. 2. 0.
 0. 2. 0. 1. 2. 0. 0. 2. 1. 2. 2. 2. 0. 1. 1. 0. 1. 2. 0. 2. 1. 0. 2. 0.
 0. 2. 1. 0. 2. 0. 0. 2. 0. 2. 2. 1. 0. 1. 0. 0. 2. 2. 0. 1. 2. 0. 0. 0.
 0.

In [28]:
data1 = pd.read_csv("test.csv")
x_test = data1.iloc[:,:-1].values
y_test = data1.iloc[:,-1].values

print(x_test)
print(y_test)


[[-2.88539477e-01 -3.96175646e+00]
 [-4.96710906e+00  1.21001357e+00]
 [-3.48422290e+00 -1.52994169e-01]
 [ 1.12918051e+00 -3.93536986e+00]
 [ 6.62444208e-01 -3.78190958e+00]
 [-4.07963100e+00 -6.62656495e-01]
 [ 4.02349943e+00  1.09220984e-01]
 [-1.11842974e+00 -1.38063729e+00]
 [-4.45510334e+00  5.17245919e-01]
 [-1.19161080e+00 -3.60487538e+00]
 [-2.80948075e+00  2.01958820e+00]
 [-5.80797032e+00  8.13584535e-01]
 [ 8.82407865e-01 -5.41784788e+00]
 [ 1.39623205e-01 -3.04928504e+00]
 [ 1.42411482e+00 -2.90652721e+00]
 [-1.13113389e+00 -5.55336402e+00]
 [ 2.37577749e+00 -2.16296901e+00]
 [ 1.11745326e-01 -4.69784558e+00]
 [-1.33887938e+00 -4.76452370e+00]
 [ 2.69456586e+00 -4.29811345e+00]
 [ 4.94914084e+00  4.12881642e-03]
 [-2.84033576e+00 -4.37695824e-01]
 [ 3.50460630e+00  4.20960948e-01]
 [ 4.03468249e+00 -6.74998237e-01]
 [-3.86327823e+00 -7.86034789e-01]
 [-3.09660320e-01 -4.55869935e+00]
 [ 2.23937181e+00 -4.69458680e-01]
 [ 3.26798215e+00 -2.66604042e+00]
 [-3.88534531e+00  1

In [29]:
y_pred1 = naive_bayes(x_test,classes,cls_prior,feature_stats)

for i in range(len(y_pred)):
    print(y_test[i],end=" ")
    print(y_pred1[i],end=' ')
    print(y_test[i]==y_pred[i])

2.0 2.0 True
1.0 1.0 True
1.0 1.0 True
2.0 2.0 True
2.0 2.0 True
1.0 1.0 True
0.0 0.0 True
1.0 2.0 False
1.0 1.0 True
2.0 2.0 True
1.0 1.0 True
1.0 1.0 True
2.0 2.0 True
2.0 2.0 True
2.0 2.0 True
2.0 2.0 True
0.0 0.0 True
2.0 2.0 True
2.0 2.0 True
2.0 2.0 True
0.0 0.0 True
1.0 1.0 True
0.0 0.0 True
0.0 0.0 True
1.0 1.0 True
2.0 2.0 True
0.0 0.0 True
0.0 0.0 True
1.0 1.0 True
2.0 2.0 True
0.0 0.0 True
1.0 1.0 True
0.0 0.0 True
2.0 2.0 True
2.0 2.0 True
0.0 0.0 True
1.0 1.0 True
0.0 0.0 True
0.0 0.0 True
0.0 0.0 True
0.0 0.0 True
0.0 0.0 True
1.0 1.0 True
0.0 0.0 True
1.0 1.0 True
0.0 0.0 True
0.0 0.0 True
2.0 2.0 True
2.0 2.0 True
0.0 0.0 True
2.0 2.0 True
1.0 1.0 True
1.0 1.0 True
0.0 0.0 True
2.0 2.0 True
1.0 1.0 True
1.0 1.0 True
0.0 0.0 True
0.0 0.0 True
0.0 0.0 True
0.0 0.0 True
1.0 1.0 True
0.0 0.0 True
0.0 0.0 True
1.0 1.0 True
0.0 0.0 True
1.0 1.0 True
1.0 1.0 True
0.0 0.0 True
1.0 1.0 True
1.0 1.0 True
2.0 2.0 True
2.0 2.0 True
0.0 0.0 True
2.0 2.0 True
1.0 1.0 True
2.0 2.0 Tru